# Private inputs
board_layout = [
    "1", "0", "0", "0", "0",
    "1", "0", "0", "0", "0",
    "2", "0", "0", "0", "0"
]
salt = "123456789"

# Public inputs (to be filled after commitment calculation)
commitment       = "0x1199243f44c0d284b4f8c19ad0c96e5a926d2f316109d2197958b5d7212dda3c"
tile_index       = 0
tile_type_result = 1